# Generated by Django 3.2.6 on 2021-10-07 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistencia', '0003_ordemservico_sugestao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomm', '0011_product_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderSugestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='ecomm.product'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderServices', to=settings.AUTH_USER_MODEL),
        ),
    ]
