# Generated by Django 3.2.6 on 2021-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sugestao',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sugestao',
            name='phone',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
