# Generated by Django 3.2.6 on 2021-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0006_auto_20211008_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='text',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
