# Generated by Django 3.2.6 on 2021-10-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0007_serviceorder_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='text',
            new_name='txService',
        ),
    ]
