# Generated by Django 3.2.6 on 2021-08-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('ref', models.CharField(max_length=20, null=True)),
                ('nome', models.CharField(max_length=200, null=True)),
                ('publicado', models.BooleanField(default=False, null=True)),
                ('em_destaque', models.BooleanField(default=False, null=True)),
                ('visibilidade_no_catálogo', models.CharField(max_length=20, null=True)),
                ('descricao_breve', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('data_de_inicio_do_preco_promocional', models.DateField(null=True)),
                ('data_de_termino_do_preco_promocional', models.DateField(null=True)),
                ('situacao_fiscal', models.CharField(max_length=15, null=True)),
                ('classe_de_imposto', models.CharField(max_length=20, null=True)),
                ('em_stock', models.BooleanField(default=True, null=True)),
                ('stock', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('valor_de_stock_baixo', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('permitir_encomendas_pendentes', models.BooleanField(default=True)),
                ('vender_individualmente', models.BooleanField(default=True)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comprimento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('permitir_avaliacoes_de_clientes', models.BooleanField(default=True)),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('preco_normal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('etiquetas', models.ImageField(blank=True, null=True, upload_to='etiquetas/')),
                ('classes_de_envio', models.CharField(max_length=20, null=True)),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('limite_de_descarregamento', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('dias_para_expirar_o_descarregamento', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('pai', models.CharField(max_length=20, null=True)),
                ('produtos_agrupados', models.CharField(max_length=50, null=True)),
                ('aumenta_vendas', models.BooleanField(default=False, null=True)),
                ('vendas_cruzadas', models.BooleanField(default=False, null=True)),
                ('url_externo', models.URLField(null=True)),
                ('texto_do_botao', models.CharField(max_length=15, null=True)),
                ('posicao', models.CharField(max_length=20, null=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecomm.category')),
            ],
        ),
    ]
