# Generated by Django 3.2.6 on 2021-08-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nota_da_encomenda',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='limite_de_descarregamento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='valor_de_stock_baixo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True),
        ),
    ]
