# Generated by Django 3.2.6 on 2021-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
