# Generated by Django 3.2.6 on 2021-08-12 01:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_alter_product_url_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_externo',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='id'),
        ),
    ]
