# Generated by Django 3.2.6 on 2021-09-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecomm.marca'),
            preserve_default=False,
        ),
    ]
